### ISSUE TITLE
Panels don't show help text

### ISSUE THREAD

**Issue by thelevicole** [optimistdigital/nova-settings#61] opened 2021-05-19 16:54 UTC
I'm running into the issue where I have fields within a `\Laravel\Nova\Panel` using the `help()` method however, this does not appear to render.

Example:
```php
NovaSettings::addSettingsFields([
  Panel::make(__('Settings group'), [
    Text::make(__('Example field'), 'example'),
  ])->help('This panel help text does not render.'),
]);
```

Expected result:
![expected](https://i.imgur.com/t5F7Pq9.png)

Actual result:
![actual](https://i.imgur.com/pgLSAr4.png)

**Comment by Tarpsvo** [comment] 2021-06-18 13:58
Heya! Thanks for reporting this. The issue is now fixed in version 3.2.0. Good luck!

**Closed by Tarpsvo** 2021-06-18 13:58 UTC
